//hii this is only for commiting code online 
function sum (a, b) {
    return a + b;
}
console.log(sum(4, 8)); // 12
console.log(sum(10, 20)); // 30

// End of the code

let ans = 0;
for (let i = 0; i <= 100; i++) {
    ans += i;
}
console.log(ans);
    if (allPeople[i].gender === "male") {   
        console.log(allPeople[i].firstName);
    }
}
let ans = 0;
for (let i = 0; i <= 100; i++) {
    ans += i;
}
console.log(ans);    


// for loop example

let ans = 0;
for (let i = 0; i <= 100; i++) {
    ans += i;
}
console.log(ans);

function sum (a, b) {
    return a + b;
}
console.log(sum(4, 8)); // 12
console.log(sum(10, 20)); // 30

let arr = [1, 2, 3, 4, 5, 6, 7, 8, 9];
for (let i = 0; i < arr.length; i++) {
    if(arr[i] % 2 === 0){
        console.log(arr[i]);
    }
}


let arr = [1, 2, 3, 4, 5, 6, 7, 8, 9];
for (let i = 0; i < arr.length; i++) {
    if(arr[i] % 2 === 0){
        console.log(arr[i]);
    }
}