//hii this is only for commiting code online 
function sum (a, b) {
    return a + b;
}
console.log(sum(4, 8)); // 12
console.log(sum(10, 20)); // 30

// End of the code

let ans = 0;
for (let i = 0; i <= 100; i++) {
    ans += i;
}
console.log(ans);
    if (allPeople[i].gender === "male") {   
        console.log(allPeople[i].firstName);
    }
}
let ans = 0;
for (let i = 0; i <= 100; i++) {
    ans += i;
}
console.log(ans);    